# Generated by Django 4.2 on 2023-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "isbn",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ISBN"
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("E", "Электронный"), ("P", "Бумажный")],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "pages_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="number of pages"
                    ),
                ),
                (
                    "publishing_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="the year of publishing"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("translator", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "publisher",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="publishing house",
                    ),
                ),
                ("works", models.ManyToManyField(to="website.work")),
            ],
        ),
    ]
