name: test_bibliophile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_project:
    runs-on: ubuntu-latest  # operating system your code will run on
    strategy:
      max-parallel: 4
      matrix:
        python-version: '3.10'  # '3.8', '3.9', '3.10',
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/setup-python@v4
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
    - name: Run Tests
      working-directory: ./project
      run: |
            python manage.py test
#        run: pytest . # run pytest test
